name: Conventional PR Title
author: DFINITY SDK Team <sdk@dfinity.org>
description: Ensure your PR title matches the Conventional Commits spec (https://www.conventionalcommits.org/).
inputs:
  success-state:
    description: Description of the status check if validation succeeds.
    required: false
    default: Title follows the specification.
  failure-state:
    description: Description of the status check if validation fails.
    required: false
    default: Title does not follow the specification.
  context-name:
    description: Persistent status check context key
    required: false
    default: conventional-pr-title
runs:
  using: docker
  image: Dockerfile
branding:
  icon: shield
  color: green
